
stages:
  - build_stage
  - stage_deploy
  - prod_deploy

build_project:
  stage: build_stage
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk update && apk add git
  script:
    - echo "Creating production build"
    # Check if the container exists before stopping it
    - docker ps -a | grep build-process && docker stop build-process > /dev/null 2>&1 || true
    - docker rm build-process > /dev/null 2>&1 || true
    - docker rmi build-process:latest > /dev/null 2>&1 || true
    - docker build -t build-process:latest .
    - docker run -itd --name build-process -v "$(pwd):/code" -p 2001:80 build-process:latest
    - ls -ltrha
  artifacts:
    paths:
      - build
    when: on_success
    expire_in: 30 days
  tags:
    - docker-builder

build_image:
  stage: build_stage
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk update && apk add git
  script:
    - echo "Creating production docker image"
    - docker login docker.imz.world -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t docker.imz.world/event-console/console:latest .
    - docker push docker.imz.world/event-console/console:latest
  tags:
    - docker-builder

staging:
  stage: stage_deploy
  before_script:
    - git fetch --all
  script:
    - echo "Staging build......"
    - docker stop console-stageing > /dev/null 2>&1
    - docker rm console-stageing > /dev/null 2>&1
    - docker rmi docker.imz.world/event-console/console:latest > /dev/null 2>&1
    - docker pull docker.imz.world/event-console/console:latest
    - docker run -itd --name console-stage-frontend -p 2001:80 docker.imz.world/event-console/console:latest
  tags:
    - shell-builder

deploy:
  stage: prod_deploy
  before_script:
    - git fetch --all
  script:
    - echo "Production deploy stage"
    - docker stop console-stageing > /dev/null 2>&1
    - docker rm console-stageing > /dev/null 2>&1
    - docker rmi docker.imz.world/event-console/console:latest > /dev/null 2>&1
    - docker pull docker.imz.world/event-console/console:latest
    - docker run -itd --name console-prod-frontend -p 2002:80 docker.imz.world/event-console/console:latest
  when: manual
  tags:
    - shell-builder


